# Generated by Django 3.1.2 on 2020-10-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name_chr', models.CharField(max_length=150)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('analize_date', models.DateTimeField()),
                ('analize_bool', models.BooleanField()),
                ('structure_txt', models.TextField(blank=True)),
            ],
        ),
    ]
