# Generated by Django 3.1.2 on 2020-10-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_table',
            name='analize_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
