# Generated by Django 3.1.2 on 2020-10-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ocr_app', '0003_auto_20201027_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_table',
            name='analize_bool',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
