# Generated by Django 3.1.2 on 2020-10-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_ocr_app', '0004_auto_20201027_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_table',
            name='analize_bool',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
